services:
  mediapipe-model-maker:
    build:
      context: .
      dockerfile: Dockerfile
    image: mediapipe-model-maker
    volumes:
      - .:/object-detection
    command: python train.py --export-fp16
