services:
  mediapipe-model-maker:
    build:
      context: .
      dockerfile: Dockerfile
    image: mediapipe-model-maker
    volumes:
      - .:/object-detection
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: python train.py --export-fp16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
